MyFirstMVCApp/Models/DogViewModel.cs
namespace MyFirstMVCApp.Models
{
    public class DogViewModel
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

MyFirstMVCApp/Models/ErrorViewModel.cs
namespace MyFirstMVCApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyFirstMVCApp/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstMVCApp.Models;

namespace MyFirstMVCApp.Controllers
{
    public class HelloWorldController : Controller
    {
        private static List<DogViewModel> dogs = new List<DogViewModel>();
        private static List<string> images = new List<string>() {
            "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg",
            "https://cdn.britannica.com/79/232779-050-6B0411D7/German-Shepherd-dog-Alsatian.jpg",
            "https://www.princeton.edu/sites/default/files/styles/scale_1440/public/images/2022/02/KOA_Nassau_2697x1517.jpg?itok=lA8UuoHt",
            "https://img.freepik.com/free-photo/shallow-focus-vertical-shot-cute-golden-retriever-puppy-sitting-grass-ground_181624-27259.jpg",
            "https://www.humanesociety.org/sites/default/files/2019/02/dog-451643.jpg",
            "https://media-cldnry.s-nbcnews.com/image/upload/t_focal-760x428,f_auto,q_auto:best/mpx/2704722219/2023_11/1700486907837_tdy_news_8a_kreutz_mystery_dog_illness_231120_1920x1080-ggrpnf.jpg",
            "https://hips.hearstapps.com/hmg-prod/images/small-fluffy-dog-breeds-maltipoo-663009b6293cc.jpg?crop=0.668xw:1.00xh;0.143xw,0&resize=980:*",
        };

        public IActionResult Index()
        {
            return View(dogs);
        }

        public IActionResult Create()
        {
            DogViewModel dogVm = new DogViewModel();
            return View(dogVm);
        }

        public IActionResult CreateDog(DogViewModel dogViewModel)
        {
            //return View("Index");
            dogs.Add(dogViewModel);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Image()
        {
            
            return View(model: images);
        }

       
    }
}

MyFirstMVCApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstMVCApp.Models;
using System.Diagnostics;

namespace MyFirstMVCApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyFirstMVCApp/Views/HelloWorld/Create.cshtml
@model DogViewModel

<h1>Create</h1>

<hr />

<div class="row">
    <div class="col-6">

        <div class="card">
            <div class="card-header">
                <h5>Create a new dog</h5>
            </div>

            <div class="card-body">
                <form asp-controller="HelloWorld" asp-action="CreateDog" method="post">
                    <div class="mb-3">
                        <label class="form-label">Dog Name</label>
                        <input asp-for=Name type="text" class="form-control" />
                    </div class="mb-3">

                    <div class="mb-3">
                        <label class="form-label">Dog Age</label>
                        <input asp-for=Age type="number" class="form-control" />
                    </div>

                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>

            <div class="card-footer">
            </div>
        </div>

    </div>
</div>

MyFirstMVCApp/Views/HelloWorld/Image.cshtml
@model List<string>

<h1>Top 10 images of dogs</h1>
<p>This page shows us lovely dogs</p>

<div class="d-flex flex-row flex-wrap gap-3 w-100 p-3 bg-image hover-overlay hover-zoom hover-shadow ripple ">

    @foreach (var im in @Model)
    {
        <div class="image-container">
            <img src="@im" alt="Lovely Dog" class="img-fluid hover-image" />
        </div>
    }

</div>

MyFirstMVCApp/Views/HelloWorld/Index.cshtml
@model List<MyFirstMVCApp.Models.DogViewModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Hello World</h1>
<p>This is the index page of HelloWorldController</p>

<ul>

    @foreach (var dog in Model)
    {
        <li>
            @dog.Name (@dog.Age)
        </li>
    }
</ul>

MyFirstMVCApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyFirstMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstMVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="HelloWorld" asp-action="Index">DogApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Index">Dog List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Create">Create Dog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Image">Dog Images</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyFirstMVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>